window.APP_CONFIG = {
  authMode: "supabase",
  courseSlug: "curso-eletronica-completo",
  siteUrl: "https://nazireu007.github.io/academia-dr-eletronica/",
  supabaseUrl: "https://hutetmamelqxinufydvv.supabase.co",
  supabaseAnonKey: "sb_publishable_cQCdgrTzOD0UwXWYYob_Pw_rEncKZGG",
  commerceMode: "hybrid",
  offerTitle: "Curso completo com acesso individual",
  offerCopy:
    "Area premium com progresso salvo, quiz final, certificado e acesso individual por aluno.",
  priceLabel: "R$ 197",
  billingLabel: "pagamento unico",
  paymentProviderLabel: "Checkout direto",
  checkoutUrl: "",
  hotmartCheckoutUrl: "",
  hotmartMembersUrl: "",
  whatsappNumber: "",
  whatsappMessage: "Ola! Quero comprar o Curso Completo de Eletronica.",
  freeModuleNumbers: ["01"],
  previewLessonIds: [],
};
