window.APP_CONFIG = {
  authMode: "supabase",
  courseSlug: "curso-eletronica-completo",
  siteUrl: "https://nazireu007.github.io/academia-dr-eletronica/",
  supabaseUrl: "https://rncboydsbikprypssbkj.supabase.co",
  supabaseAnonKey: "sb_publishable_NoROjbognmiGh0XBYX0Acg_pOLr1FO5",
  commerceMode: "hybrid",
  offerTitle: "Comece grátis e avance para o premium quando quiser",
  offerCopy:
    "Crie sua conta gratuita para estudar com anúncios. Quando quiser zero anúncios e certificado de conclusão, ative o plano premium por R$ 19,99.",
  priceLabel: "R$ 19,99",
  billingLabel: "pagamento único",
  merchantBrand: "Nitro Scan Pro",
  paymentProviderLabel: "Cartão ou PicPay",
  checkoutUrl: "https://link.picpay.com/p/177697905069ea8c6a0ab11",
  hotmartCheckoutUrl: "",
  hotmartMembersUrl: "",
  whatsappNumber: "5581997567964",
  whatsappMessage: "Ola! Quero ativar o plano premium do Curso Completo de Eletronica por R$ 19,99.",
  pixKey: "NAZIREURODRIGUEZ@GMAIL.COM",
  freePlanLabel: "Conta gratuita",
  premiumPlanLabel: "Plano premium",
  adsEnabled: true,
  adNetwork: "adsterra",
  adSenseClient: "",
  adsterraPublicMarkup:
    '<script>atOptions = {\'key\' : \'b3ffe15cd80e0f0fb5de5871d8072ec5\',\'format\' : \'iframe\',\'height\' : 250,\'width\' : 300,\'params\' : {}};</script><script src="https://www.highperformanceformat.com/b3ffe15cd80e0f0fb5de5871d8072ec5/invoke.js"></script>',
  adsterraDashboardMarkup:
    '<script>atOptions = {\'key\' : \'b3ffe15cd80e0f0fb5de5871d8072ec5\',\'format\' : \'iframe\',\'height\' : 250,\'width\' : 300,\'params\' : {}};</script><script src="https://www.highperformanceformat.com/b3ffe15cd80e0f0fb5de5871d8072ec5/invoke.js"></script>',
  adsterraLessonMarkup: "",
  adsterraPublicMobileMarkup:
    '<script>atOptions = {\'key\' : \'1cb76908544f6267c48a5befc8367e32\',\'format\' : \'iframe\',\'height\' : 50,\'width\' : 320,\'params\' : {}};</script><script src="https://www.highperformanceformat.com/1cb76908544f6267c48a5befc8367e32/invoke.js"></script>',
  adsterraSocialBarMarkup: "",
  freeModuleNumbers: ["01"],
  previewLessonIds: [],
};
